name: cloudfprint
version: '0.1'
summary: Bitrix24 Cloud Cash Machine # 79 char long summary
description: |
  This app connect your cash machine to Bitrix24
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./fptr500.png
apps:      
  cloudfprint:
    command: usr/lib/jvm/default-java/bin/java -jar $SNAP/cloudfprint.jar start
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/jre/bin:$PATH:$SNAP/libs
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  fptr10_t:
    command: $SNAP/libs/fptr10_t.sh
    plugs: [network, network-bind, desktop]

parts:
  assets:
    source: assets/
    plugin: dump
    stage-packages:
      - default-jdk
      - ca-certificates
      - ca-certificates-java
  