name: cloudfprint
#base: core18
#title: Bitrix24 Cloud Cash Machine
architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
version: '0.1'
summary: Bitrix24 Cloud Cash Machine # 79 char long summary
description: |
  This app connect your cash machine to Bitrix24
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./fptr500.png

apps:    
  cloudfprint:
    command: usr/lib/jvm/default-java/bin/java -Duser.language=RU -Duser.region=ru -Djava.library.path=$SNAP/libs/ -jar $SNAP/cloudfprint.jar start
    stop-command: usr/lib/jvm/default-java/bin/java -jar $SNAP/cloudfprint.jar stop
    stop-timeout: 10s
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/jre/bin:$PATH:$SNAP/libs/
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, raw-usb, hardware-observe, io-ports-control]
  fptr10:
    command: libs/fptr10_t.sh
    plugs: 
      - x11
      - opengl
      - unity7
      - home
      - network
      - network-bind

parts:
  assets:
    source: assets/
    plugin: dump
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - default-jdk
  libs:
    plugin: dump
    source:
      - on amd64: https://cloudfprint.blob.core.windows.net/client/amd64.zip
      - on i386:  https://cloudfprint.blob.core.windows.net/client/i386.zip
      - on armhf: https://cloudfprint.blob.core.windows.net/client/armhf.zip
      - on arm64: https://cloudfprint.blob.core.windows.net/client/arm64.zip
    source-type: zip
    after: [assets]
  