name: cloudfprint
#base: core18
#title: Bitrix24 Cloud Cash Machine
version: '0.1'
summary: Bitrix24 Cloud Cash Machine # 79 char long summary
description: |
  This app connect your cash machine to Bitrix24
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
icon: ./fptr500.png

apps:      
  cloudfprint:
    command: usr/lib/jvm/default-java/bin/java -jar $SNAP/cloudfprint.jar start
    stop-command: usr/lib/jvm/default-java/bin/java -jar $SNAP/cloudfprint.jar stop
    stop-timeout: 10s
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/jre/bin:$PATH:$SNAP/libs
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]
  fptr10:
    command: libs/fptr10_t.sh
    plugs: 
      - x11
      - opengl
      - unity7
      - home
      - network
      - network-bind

parts:
  assets:
    source: assets/
    plugin: dump
    stage-packages:
      - default-jdk
      - ca-certificates
      - ca-certificates-java
  