name: cloudfprint
base: core18
#title: Bitrix24 Cloud Cash Machine
architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
version: '2023.06.14'
summary: Bitrix24 Cloud POS # 79 char long summary
description: |
  This app connect your POS to Bitrix24
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: ./fptr500.png

apps:    
  cloudfprint:
    command: run.sh
    stop-command: stop.sh
    stop-timeout: 10s
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/jre/bin:$PATH:$SNAP/libs/
      DTO10_LOG_CONFIG_FILE: $SNAP_COMMON
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, raw-usb, hardware-observe, io-ports-control, serial-port]
  # eou:
  #   command: eou/EthOverUsb.sh -e
  #   daemon: simple
  #   restart-condition: always
  #   plugs: [network, network-bind, raw-usb, hardware-observe, io-ports-control, serial-port]

parts:
#  jar:
#    source: https://cloudfprint.blob.core.windows.net/client/cloudfprint.jar
#    plugin: dump
  assets:
    source: assets/
    plugin: dump
#    after: [jar]
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages:
      - default-jdk
      - ca-certificates
      - ca-certificates-java
  libs:
    plugin: dump
    source:
      - on amd64: https://cloudfprint.blob.core.windows.net/client/amd64.zip
      - on i386:  https://cloudfprint.blob.core.windows.net/client/i386.zip
      - on armhf: https://cloudfprint.blob.core.windows.net/client/armhf.zip
      - on arm64: https://cloudfprint.blob.core.windows.net/client/arm64.zip
    source-type: zip
    stage-packages:
      - libqt5gui5
      - zlib1g
    after: [assets]
  # eou:
  #   plugin: dump
  #   source:
  #     - on amd64: https://cloudfprint.blob.core.windows.net/client/eou-amd64.zip
  #     - on i386:  https://cloudfprint.blob.core.windows.net/client/eou-i386.zip
  #     - on armhf: https://cloudfprint.blob.core.windows.net/client/eou-armhf.zip
  #     - on arm64: https://cloudfprint.blob.core.windows.net/client/eou-armhf.zip
  #   source-type: zip
  #   after: [assets]
  
