#!/bin/sh

echo '<?xml version="1.0" encoding="utf-8" ?>' > eou/settings.xml
echo '<settings>' >> eou/settings.xml
echo '<hotplug>auto</hotplug>' >> eou/settings.xml
echo '<logs><dir>' >> eou/settings.xml
echo $SNAP_USER_COMMON >> eou/settings.xml
echo '/EoU</dir></logs>' >> eou/settings.xml
echo '</settings>' >> eou/settings.xml